### ISSUE TITLE
Project metadata does not save

### ISSUE THREAD

**Issue by sunehajagan** [Blue-Marine-Foundation/Maerl#125]
Edits on project metadata table are not being saved on Mearl ("Save Changes" button not working) 
![Image](https://github.com/user-attachments/assets/08e60383-69f3-44aa-9714-30da48db6f6c)

**Comment by samjamead** [comment]
Thanks for flagging! This was caused by a little bug that didn't like saving the form if there were no local contacts. Fixed now! Thank you
