### ISSUE TITLE
Add updates window edits

### ISSUE THREAD

**Issue by AW-BLUE** [Blue-Marine-Foundation/Maerl#26]
- [x] When opens up, automatically assumes impact indicator rather than progress indicator
- [ ] #46
- [ ] #47
- [x] where they need to input the number - have some text to indicate they need to type there
- [x] include 'unit: ' before the number of beneficiaries (maybe, open to your suggestions)
- [x] Maybe change link text (although Anna wants you to keep it)

**Comment by samjamead** [comment]
Closed and created two separate issues. For new issue #46 let's see how often this happens before making the default empty (a bit part of intuition in forms is seeing a 'correct' answer modelled. It's easier to change a 'wrong' entry than add something to a blank entry). For #47 this will be handled elsewhere (i.e. in the database, and then unplanned outputs will always be an option).
