### ISSUE TITLE
logframe page structure

### ISSUE THREAD

**Issue by AW-BLUE** [Blue-Marine-Foundation/Maerl#35]
want to make edits to make the flow between different tiers a bit clearer and also to make more visible within one screen.  I still don't have it entirely clear how this might look so I don't know whether perhaps it's worth having a chat about this and seeing if we can find examples (I'm not currently sure what's best to google).

**Comment by samjamead** [comment]
Fixed by c72e96b introducing TOC view. Further work on TOC view as part of #51
