### ISSUE TITLE
Remove project name from updates list and condense

### ISSUE THREAD

**Issue by AW-BLUE** [Blue-Marine-Foundation/Maerl#64]
On the project updates tab (https://maerl.vercel.app/app/projects/berwickshire/updates) remove the 'Berwickshire' label and condense list a little more and have header at top of list to make clear what the codes/numbers are plss

**Comment by samjamead** [comment]
- [ ] Add heading to the right hand side of the list
- [ ] Remove project name tag
- [ ] (Try?!) to futher condense the list 
- [ ] Add impact stat to row
